# .github/workflows/devsecops.yml 
name: DevGuard DevSecOps

on:
    push:

permissions:
    contents: read
    packages: write

jobs:
    devguard:
        uses: l3montree-dev/devguard-action/.github/workflows/full.yml@main
        with:
            asset-name: "l3montree-cybersecurity/projects/l3montree-intern/assets/oss-events"
            api-url: https://api.main.devguard.org
            continue-on-open-code-risk: true
        secrets:
            devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" # you need to create this secret in your GitHub repository settings
