# .github/workflows/devsecops.yml 
name: DevGuard DevSecOps

on:
    push:

permissions:
    contents: read
    packages: write

jobs:
    find-leaked-secrets:
        uses: l3montree-dev/devguard-action/.github/workflows/secret-scanning.yml@main
        with:
            asset-name: "l3montree-dev/software-security-events-bonn-website"
            api-url: https://api.main.devguard.org
        secrets:
            devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" # you need to create this secret in your GitHub repository settings

    dependency-scanning:
        uses: l3montree-dev/devguard-action/.github/workflows/software-composition-analysis.yml@main
        with:
            asset-name: "l3montree-dev/software-security-events-bonn-website"
            api-url: https://api.main.devguard.org
        secrets:
            devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" # you need to create this secret in your GitHub repository settings

    container-scanning:
        uses: l3montree-dev/devguard-action/.github/workflows/container-scanning.yml@main
        with:
            asset-name: "l3montree-dev/software-security-events-bonn-website"
            api-url: https://api.main.devguard.org
        secrets:
            devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" # you need to create this secret in your GitHub repository settings

    bad-practice-finder:
        uses: l3montree-dev/devguard-action/.github/workflows/sast.yml@main
        with:
            asset-name: "l3montree-dev/software-security-events-bonn-website"
            api-url: https://api.main.devguard.org
        secrets:
            devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" # you need to create this secret in your GitHub repository settings

    infrastructure-as-code-scanning:
        uses: l3montree-dev/devguard-action/.github/workflows/iac.yml@main
        with:
            asset-name: "l3montree-dev/software-security-events-bonn-website"
            api-url: https://api.main.devguard.org
        secrets:
            devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" # you need to create this secret in your GitHub repository settings

    build-image:
        uses: l3montree-dev/devguard-action/.github/workflows/build-image.yml@main
        with:l3montree-dev/software-security-events-bonn-website            asset-name: "l3montree-dev/software-security-events-bonn-website"
            api-url: https://api.main.devguard.org
        secrets:
            devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" # you need to create this secret in your GitHub repository settings 
